### PR TITLE
Sort a cell by it's `datetime` attribute if one exists

### LINKED ISSUE #206: Sort by date does don't use 'datetime' value of <time> elements
## What
Using o-date on time elements in a column converts the text to a relative time string. While sorting by date should still work for 'ft time' strings it does not work for these relative times.

Would it be more efficient, and more general/correct to first take the datetime value from any o-date/<time> elements and use that to sort by, falling back to coercing text to a date?

### PR DESCRIPTION
**Pull request by JakeChampion**
This attribute is on `time` elements and is the machine-readable version of the date/time, ideal for using as the value to sort by.

This closes #206

### CODE REVIEW

File: src/js/Sort/CellFormatter.js [hunk 1]
```diff
@@ -19,18 +19,19 @@ function extractAltFromImages(cell){
...
+ * 	extractText('<span class="o-icons-icon o-icons-icon--tick" title="Correct"></span>'); //Correct
+ * 	extractText('<span class="o-icons-icon o-icons-icon--tick" aria-label="Correct"></span>'); //Correct
+ * 	extractText('<time class="o-date" data-o-component="o-date" datetime="2020-06-19T07:56:18Z">2 hours ago</time>'); //Correct
  * @param {HTMLElement} cell The DOM node to operate on, possibly a <td>
  * @access private
  * @returns {HTMLElement} text representation of the HTML node
  */
 function extractText(cell){
-	let text = cell.textContent.trim();
+	let text = cell.dateTime || cell.textContent.trim();
```
Comment (notlee) [inline src/js/Sort/CellFormatter.js:34]: I don't think this will solves Rhys issue as `ftDateTimeToNumber` can only parse FT formatted dates. We don't include a date parsing library

Comment (notlee) [reply src/js/Sort/CellFormatter.js:34]: They could set `data-o-table-sort-value` to the UNIX Epoch though

https://github.com/Financial-Times/o-table#custom-sort-declarative

File: src/js/Sort/CellFormatter.js [hunk 2]
```diff
@@ -174,6 +174,24 @@ function ftDateTimeToNumber(text) {
...
+ *  dateTimeToNumber('2011-11') //UNIX epoch, first of month
+ *  dateTimeToNumber('2011-11-18T14:54') //UNIX epoch including time
+ *  dateTimeToNumber('14.54') //14.54
+ *  dateTimeToNumber('Not a known date') //Note a known date
+ * @param {String} text The datetime string to operate on
+ * @access private
+ * @returns {Number|String} Number representation of datetime string or the original datetime string if it could not be turned into a number.
+ */
+function dateTimeToNumber(text) {
+	const dateObj = new Date(text);
```
Comment (notlee) [inline src/js/Sort/CellFormatter.js:191]: I think whilst working on `o-table` I dismissed `Date` because of this MDN warning:

>It is not recommended to use Date.parse as until ES5, parsing of strings was entirely implementation dependent. There are still many differences in how different hosts parse date strings, therefore date strings should be manually parsed (a library can help if many different formats are to be accommodated).

But how silly, we live in the future now! 🙈

File: src/js/Sort/CellFormatter.js [hunk 3]
```diff
@@ -150,10 +157,11 @@ function ftDateTimeToNumber(text) {
 	const time = text.match(/(?:\s|^)(\d{1,2}(?:[.](\d{2}))?)(pm|am)$/);
 	// Get date.
 	const month = date && date[1] ? date[1] : null;
-	// Get full month name from a given month e.g. 'January' for 'Jan'.
-	const matchingMonthNames = monthNames.filter((name) => name.indexOf(month) !== -1);
-	// Get the index of the matching month name.
-	const monthIndex = matchingMonthNames && matchingMonthNames[0] ? monthNames.indexOf(matchingMonthNames[0]) : null;
+	// Get index of the month name from a given month e.g. 'January' for 'Jan'.
+	let monthIndex = month && monthNames.findIndex((name) => name.startsWith(month));
```
Comment (notlee) [inline src/js/Sort/CellFormatter.js:161]: breaking release alert, IE11 doesn't support `findIndex`, we'd need to require a new polyfill :(

Comment (JakeChampion) [reply src/js/Sort/CellFormatter.js:161]: I've added a migration guide :-)

File: README.md [hunk 4]
```diff
@@ -512,8 +512,9 @@ Known issues:
 
 State | Major Version | Last Minor Release | Migration guide |
 :---: | :---: | :---: | :---:
-✨ active | 8 | N/A | [migrate to v8](MIGRATION.md#migrating-from-v7-to-v8) |
-⚠ maintained | 7 | 7.4 | [migrate to v7](MIGRATION.md#migrating-from-v6-to-v7) |
+✨ active | 9 | N/A | [migrate to v9](MIGRATION.md#migrating-from-v8-to-v9) |
+⚠ maintained | 8 | 0.11 | [migrate to v8](MIGRATION.md#migrating-from-v7-to-v8) |
```
Comment (JakeChampion) [inline README.md:516]:
```suggestion
⚠ maintained | 8 | 8.0.11 | [migrate to v8](MIGRATION.md#migrating-from-v7-to-v8) |
```

File: test/Sort/TableSorter.test.js [hunk 5]
```diff
@@ -170,6 +171,30 @@ describe("BaseTable", () => {
 			assertSortOrder({sortOrder, columnIndex, expected}).catch(done).finally(done);
 		});
 
+		it.only('sorts "date" type with based on dateTime attribute', done => {
```
Comment (JakeChampion) [inline test/Sort/TableSorter.test.js:174]:
```suggestion
		it('sorts "date" type with based on dateTime attribute', done => {
```

**Comment by notlee** [comment]
Do you think it's worth a major release to allow us to use `findIndex`? In theory we shouldn't be scared of major releases and should make them frequently but in reality it's often a hassle for our users. In this case I think the trade-off is in favor of not breaking and delivering this update to users automatically, but open to discussion :)

**Comment by JakeChampion** [comment]
> Do you think it's worth a major release to allow us to use `findIndex`? In theory we shouldn't be scared of major releases and should make them frequently but in reality it's often a hassle for our users. In this case I think the trade-off is in favor of not breaking and delivering this update to users automatically, but open to discussion :)

I can rewrite this to be not a breaking change, sure thing.

When do you think it will be fine for Origami to start doing more frequent and smaller breaking changes such as this?

**Comment by notlee** [comment]
>When do you think it will be fine for Origami to start doing more frequent and smaller breaking changes such as this?

Great question. I'd like to see users get Renovate/Dependabot PRs for Origami projects but moving to npm is not enough due to flatness and the cascade. It also wouldn't help Build Service users. I think we need to prioritise figuring this out. Doing so meets our current objectives but I don't know if we have capacity.

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v8.1.0 :tada:
